apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dragonfly
  namespace: nova-torch
  labels:
    app: dragonfly
    component: database
    version: "latest"
spec:
  serviceName: dragonfly-service
  replicas: 3  # HA configuration with 3 nodes
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: dragonfly
      component: database
  template:
    metadata:
      labels:
        app: dragonfly
        component: database
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6379"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
        
      containers:
      - name: dragonfly
        image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
        imagePullPolicy: Always
        
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        - name: metrics
          containerPort: 9999
          protocol: TCP
          
        args:
        - "--alsologtostderr"
        - "--cluster_mode=yes"
        - "--port=6379"
        - "--admin_port=9999"
        - "--admin_nopass"
        - "--maxmemory=4gb"
        - "--proactor_threads=4"
        - "--snapshot_cron=0 */6 * * *"  # Snapshot every 6 hours
        - "--dir=/data"
        - "--dbfilename=dump"
        - "--requirepass=$(DRAGONFLY_PASSWORD)"
        
        env:
        - name: DRAGONFLY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nova-torch-secrets
              key: dragonfly-password
              
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
            
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(DRAGONFLY_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(DRAGONFLY_PASSWORD)
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/dragonfly
          readOnly: true
          
      volumes:
      - name: config
        configMap:
          name: dragonfly-config
          
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: dragonfly
        component: database
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd  # Use fast SSD storage
      resources:
        requests:
          storage: 100Gi
          
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-service
  namespace: nova-torch
  labels:
    app: dragonfly
    component: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: metrics
    port: 9999
    targetPort: metrics
  selector:
    app: dragonfly
    component: database
    
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-lb
  namespace: nova-torch
  labels:
    app: dragonfly
    component: database
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: dragonfly
    component: database
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dragonfly-config
  namespace: nova-torch
  labels:
    app: dragonfly
    component: database
data:
  dragonfly.conf: |
    # DragonflyDB Configuration
    # Nova-Torch Production Settings
    
    # Memory settings
    maxmemory 4gb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Cluster settings
    cluster-enabled yes
    cluster-node-timeout 5000
    cluster-replica-validity-factor 10
    cluster-migration-barrier 1
    cluster-require-full-coverage yes
    
    # Performance
    tcp-keepalive 300
    timeout 0
    tcp-backlog 511
    
    # Security
    protected-mode yes
    
    # Logging
    loglevel notice
    logfile ""
    syslog-enabled no
    
    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dragonfly-pdb
  namespace: nova-torch
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: dragonfly
      component: database