apiVersion: v1
kind: Secret
metadata:
  name: nova-torch-secrets
  namespace: nova-torch
  labels:
    app: nova-torch
    component: secrets
type: Opaque
stringData:
  # NOTE: In production, use external secret management (Vault, AWS Secrets Manager, etc.)
  # This is a template - replace with actual base64 encoded values
  dragonfly-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-torch-tls
  namespace: nova-torch
  labels:
    app: nova-torch
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificates for internal communication
  # Generate with: kubectl create secret tls nova-torch-tls --cert=tls.crt --key=tls.key
  tls.crt: ""
  tls.key: ""